#!/usr/bin/env node
// Build the static GitHub Pages demo into docs/ (no server: app.js swaps in its in-browser mock API).
//   node scripts/build-pages.js
// Copies public/ with relative paths (works under https://<user>.github.io/<repo>/), writes a subpath-safe manifest
// and service worker, and docs/demo-deck.json = the generic SAMPLE deck + the built-in feedback card (gestures resolved).
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const core = require('../lib/core');
const sampleCards = require('./sample-cards');
const ROOT = path.join(__dirname, '..');
const PUB = path.join(ROOT, 'public');
const OUT = path.join(ROOT, 'docs');

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });
const copy = (rel) => fs.cpSync(path.join(PUB, rel), path.join(OUT, rel), { recursive: true });
['app.js', 'favicon.ico', 'fonts', 'icons'].forEach(copy);

// demo deck: same samples as the server demo, sorted like /api/deck, feedback card last. "{date}" -> today (ET) in the browser.
const now = new Date();
const day = core.etDate(now);
const cards = core.sortDeck(sampleCards(now).map((raw) => core.validateCard(raw, now).card))
  .map((c) => ({ ...c, createdAgoMin: Math.round((now - Date.parse(c.createdAt)) / 60000) }));
cards.push({ ...core.feedbackCard(day), createdAgoMin: 0 });
const deck = {
  note: 'Generated by scripts/build-pages.js from scripts/sample-cards.js and the built-in feedback card. Example data only.',
  cards: cards.map(({ createdAt, expiresAt, receivedAt, ...c }) => ({ ...c, id: c.id.replace(day, '{date}'), gestures: core.effectiveGestures(c) })),
};
fs.writeFileSync(path.join(OUT, 'demo-deck.json'), JSON.stringify(deck, null, 2) + '\n');

// index.html: relative asset paths + static-demo flag
let html = fs.readFileSync(path.join(PUB, 'index.html'), 'utf8')
  .replace(/(href|src)="\/(?!\/)/g, '$1="')
  .replace('<title>Morning Deck</title>', '<title>Morning Deck · demo</title>')
  .replace('<script src="app.js" defer></script>', '<script>window.MD_STATIC_DEMO = true;</script>\n  <script src="app.js" defer></script>');
if (!html.includes('MD_STATIC_DEMO')) throw new Error('could not inject MD_STATIC_DEMO');
fs.writeFileSync(path.join(OUT, 'index.html'), html);
fs.writeFileSync(path.join(OUT, 'styles.css'), fs.readFileSync(path.join(PUB, 'styles.css'), 'utf8').replace(/url\("\/fonts\//g, 'url("fonts/'));

// manifest: everything relative to the manifest URL, so scope/start_url = the repo subpath
const man = JSON.parse(fs.readFileSync(path.join(PUB, 'manifest.webmanifest'), 'utf8'));
Object.assign(man, { id: './', start_url: './?source=pwa', scope: './', name: 'Morning Deck (demo)' });
man.icons = man.icons.map((i) => ({ ...i, src: i.src.replace(/^\//, '') }));
fs.writeFileSync(path.join(OUT, 'manifest.webmanifest'), JSON.stringify(man, null, 2) + '\n');

// service worker: relative shell, network-first (always fresh online, works offline), versioned by content hash
const SHELL = ['./', 'index.html', 'styles.css', 'app.js', 'demo-deck.json', 'manifest.webmanifest', 'fonts/jakarta.woff2',
  'icons/icon-192.png', 'icons/icon-512.png', 'icons/maskable-192.png', 'icons/maskable-512.png', 'icons/favicon-32.png'];
const hash = crypto.createHash('sha256');
for (const f of SHELL.slice(1)) hash.update(fs.readFileSync(path.join(OUT, f)));
const version = 'md-pages-' + hash.digest('hex').slice(0, 10);
fs.writeFileSync(path.join(OUT, 'sw.js'), `/* Morning Deck static demo service worker (generated by scripts/build-pages.js). Paths are relative to its scope. */
const VERSION = '${version}';
const SHELL = ${JSON.stringify(SHELL)};
self.addEventListener('install', (e) => { e.waitUntil(caches.open(VERSION).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting())); });
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || !req.url.startsWith(self.registration.scope)) return;
  e.respondWith(fetch(req).then((res) => {
    if (res.ok && res.type === 'basic') { const copy = res.clone(); caches.open(VERSION).then((c) => c.put(req.mode === 'navigate' ? './' : req, copy)); }
    return res;
  }).catch(() => caches.match(req.mode === 'navigate' ? './' : req, { ignoreSearch: true }).then((r) => r || caches.match('./'))));
});
`);
fs.writeFileSync(path.join(OUT, '.nojekyll'), '');
console.log(`docs/ built: ${deck.cards.length} demo cards, sw ${version}`);
